Code/Travelancar_Kel09/Travelancar_Kel09/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Travelancar_Kel09.Controllers
{
    [Authorize] 
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Pesawat()
        {
            return View();
        }

        public ActionResult Hotel()
        {
            return View();
        }

       
    }
}

Code/Travelancar_Kel09/Travelancar_Kel09/Controllers/MawarMelatiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Travelancar_Kel09.MawarMelatiService;

namespace Travelancar_Kel09.Controllers
{
    public class MawarMelatiController : Controller
    {
        MawarMelatiServiceClient objmawar = new MawarMelatiServiceClient();
        // GET: MawarMelati
        public ActionResult MawarMelati()
        {
            ViewBag.lstHotel = objmawar.getAllDetails();
            return View();
        }

        public ActionResult Search(FormCollection fc)
        {
            string txtValue = fc["SearchValue"];
            string type = fc["TypeCollection"];
            if (type.Equals("ID"))
            {
                ViewBag.lstHotel = objmawar.getID(Convert.ToInt16(txtValue));
            }
            else
            {
                ViewBag.lstHotel = objmawar.getKotal(Convert.ToString(txtValue));
            }
            return View("KasurEmpuk");
        }
    }
}

Code/Travelancar_Kel09/Travelancar_Kel09/Controllers/PesanHotelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Travelancar_Kel09.Models;

namespace Travelancar_Kel09.Controllers
{
    public class PesanHotelController : Controller
    {
        private ModelHotel[] modelHotels =
        {
            new ModelHotel {No_Kamar = 10, Nama = "Rafika", Alamat = "Sigumpar", Email = "rafikatampubolon18@gmail.com", NoHp = "2345", CheckIn = "10-10-2000", CheckOut = "15-10-2000", Tgl_Booking = "05-10-2000"}
        };
        // GET: PesanHotel
        public ActionResult DetailHotel(int? nokmr)
        {
            ModelHotel dataHotel = modelHotels.Where(p => p.No_Kamar == nokmr).First();
            return View();
        }

        public ActionResult Booking()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Booking(ModelHotel model)
        {
            return View("DetailHotel", model);
        }
    }
}

Code/Travelancar_Kel09/Travelancar_Kel09/Controllers/PesanPesawatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Travelancar_Kel09.Models;

namespace Travelancar_Kel09.Controllers
{
    public class PesanPesawatController : Controller
    {
        private ModelPesawat[] modelPesawats =
         {
            new ModelPesawat {Id = 1, Nama = "Rafika", Email = "rafikatampubolon18@gmail.com", No_Hp = "12345", Asal = "Sigumpar", Tujuan = "Jakarta", Tgl_Berangkat = "2012-10-20" , Kelas = "Ekonomi", Nama_Maskapai = "Puyuh Air"},
            new ModelPesawat {Id = 2, Nama = "Winda", Email = "windapasaribu21@gmail.com", No_Hp = "13456", Asal = "Sibolga", Tujuan = "Jakarta", Tgl_Berangkat = "2012-10-30" , Kelas = "Ekonomi", Nama_Maskapai = "Pinguin Air"},
            new ModelPesawat {Id = 3, Nama = "Febiola", Email = "febiola@gmail.com", No_Hp = "12568", Asal = "Balige", Tujuan = "Jakarta", Tgl_Berangkat = "2012-10-21" , Kelas = "Ekonomi", Nama_Maskapai = "Itik Air"},
            new ModelPesawat {Id = 4, Nama = "Nevi", Email = "nevidel@gmail.com", No_Hp = "19807", Asal = "Dolok Sanggul", Tujuan = "Jakarta", Tgl_Berangkat = "2012-11-20" , Kelas = "Ekonomi", Nama_Maskapai = "Puyuh Air"},
        };

        public ActionResult DetailPesanan(int? id)
        {
            ModelPesawat dataItem = modelPesawats.Where(p => p.Id == id).First();
            return View(dataItem);
        }

        public ActionResult CreatePesanan()
        {
            return View(new ModelPesawat());
        }

        [HttpPost]
        public ActionResult CreatePesanan(ModelPesawat model)
        {
            return View("DetailPesanan", model);
        }
    }
}

Code/Travelancar_Kel09/Travelancar_Kel09/Views/Home/Hotel.cshtml
@{
    ViewBag.Title = "Hotel";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Hotel</title>
</head>
<body>
    <br />
    <h4><b>Selamat Datang di Hotel Travelancar</b></h4>
    <br />
    <div class="btn btn-default btn-lg" style="text-decoration-color:beige">@Html.ActionLink("Pesan Sekarang", "Booking", "PesanHotel")</div>
    <br />
    <br />
    <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
            <img src="~/Additional-file/img/empuk.jpg" />
            <div class="caption">
                <h4>@Html.ActionLink("Hotel Kasur Empuk", "KasurEmpuk", "KasurEmpuk")</h4>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-6">
        <div class="thumbnail">
            <img src="~/Additional-file/img/mawar.jpg" id="img3" />
            <div class="caption">
                <h4>@Html.ActionLink("Hotel Mawar Melati", "MawarMelati", "MawarMelati")</h4>
            </div>
        </div>
    </div>

</body>
</html>

Code/Travelancar_Kel09/Travelancar_Kel09/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
     
        .konten {
            height: 400px;
        }

        .sidebar {
            height: 400px;
        }
    </style>
</head>
<body>
    <h3 class="text-center"><b>Selamat Datang di Travelancar.com</b></h3>
    <br /> 
    <div class="col-md-9 col-xs-12 konten">
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
            </ol>

            <!-- deklarasi carousel -->
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/Additional-file/img/gbr2.jpg">

                </div>
                <div class="item">
                    <img src="~/Additional-file/img/gbr3.jpg">

                </div>
                <div class="item">
                    <img src="~/Additional-file/img/gbr4.jpg">

                </div>
            </div>

            <!-- membuat panah next dan previous -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>

    <div class="col-md-3 col-xs-12 sidebar">
        <p>Lakukan Pemesanan</p>
        <ul>
            <li>@Html.ActionLink("Tiket Pesawat", "Pesawat")</li>
            <li>@Html.ActionLink("Booking Hotel", "Hotel")</li>
        </ul>
    </div>
</body>
</html>

Code/Travelancar_Kel09/Travelancar_Kel09/Views/Home/Pesawat.cshtml
@{
    ViewBag.Title = "Pesawat";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Pesawat</title>
</head>
<body> 
    <br />
    <h4><b>Selamat Datang di Penerbangan Travelancar</b></h4>
    <br />
    <div class="btn btn-default btn-lg" style="text-decoration-color:beige">@Html.ActionLink("Pesan Sekarang", "CreatePesanan", "PesanPesawat")</div>
    <br />
    <br />
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/Additional-file/img/puyuh.jpg" />
            <div class="caption">
                <h4>@Html.ActionLink("Maskapai Puyuh Air", "PuyuhAir", "PuyuhAir")</h4>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/Additional-file/img/itik.jpg" id="img3" />
            <div class="caption">
                <h4>@Html.ActionLink("Maskapai Itik Air", "ItikAir", "ItikAir")</h4>
            </div>
        </div>
    </div>

    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <img src="~/Additional-file/img/piguin.jpg" id="img2" />
            <div class="caption">
                <h4>@Html.ActionLink("Maskapai Penguin Air", "PinguinAir", "PinguinAir")</h4>
            </div>
        </div>
    </div>

</body>
</html>